config/routes.rb
Rails.application.routes.draw do
  resources :people, only: %i[index show]
  resources :planets, only: %i[index show]
  resources :species, only: %i[index show]
  resources :starships, only: %i[index show]
  root to: 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :starship_possessions, dependent: :destroy
  has_many :starships, through: :starship_possessions

  has_many :species_people, dependent: :destroy
  has_many :species, through: :species_people

  has_many :planet_people, dependent: :destroy
  has_many :planets, through: :planet_people

  validates :name, :birth_year, :eye_color, :gender, :hair_color, :height, :mass, :skin_color, :url, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :planet_people, dependent: :destroy
  has_many :people, through: :planet_people

  has_many :species_planets, dependent: :destroy
  has_many :species, through: :species_planets

  validates :name, :diameter, :rotation_period, :orbital_period, :gravity, :climate, :terrain, :surface_water, :url, presence: true
end

app/models/planet_person.rb
class PlanetPerson < ApplicationRecord
  belongs_to :planet
  belongs_to :person
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :species_people, dependent: :destroy
  has_many :people, through: :species_people

  has_many :species_planets, dependent: :destroy
  has_many :planets, through: :species_planets

  validates :name, :classification, :designation, :average_height, :average_lifespan, :eye_colors, :hair_colors, :skin_colors, :language, :url, presence: true
end

app/models/species_person.rb
class SpeciesPerson < ApplicationRecord
  belongs_to :person
  belongs_to :species
end

app/models/species_planet.rb
class SpeciesPlanet < ApplicationRecord
  belongs_to :species
  belongs_to :planet
end

app/models/starship.rb
class Starship < ApplicationRecord
  has_many :starship_possessions, dependent: :destroy
  has_many :people, through: :starship_possessions

  validates :name, :model, :starship_class, :manufacturer, :cost_in_credits, :length, :crew, :passengers, :max_atmosphering_speed, :hyperdrive_rating, :MGLT, :cargo_capacity, :consumables, :url, presence: true
end

app/models/starship_possession.rb
class StarshipPossession < ApplicationRecord
  belongs_to :person
  belongs_to :starship
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
  end

  def show
    @species = Species.find(params[:id])
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def index
    @starships = Starship.all
  end

  def show
    @starship = Starship.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>StarWarsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="container mt-3"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/people/index.html.erb
<div class="row justify-content-center">
  <h1>
    <span id="banner-typed-text"></span>
  </h1>
</div>
<div class="row justify-content-center">
  <% @people.each do |person| %>
    <div class="card m-3 col-10 col-md-3 col-lg-2">
      <div>
        <h2><%= link_to person.name, person_path(person) %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/people/show.html.erb
<div class="row justify-content-center">
  <h1 class="mt-3"><%= @person.name %></h1>
</div>

<div class="mt-5 row card-show justify-content-center">
    <h3>
      Hi! My name is <%= @person.name %>.

      <%# Checking Person's species. If it exists, post it. %>
      <% if @person.species.first %>
        I'm a <%= @person.species.first.name %>.
      <% end %>

      <%# Checking Person's homeworld. If it exists, post it. %>
      <% if @person.planets.first.name != "unknown" %>
        I was born in <%= @person.planets.first.name %>
      <% else %>
        I don't know where I was born, but it happened in
      <% end %>

      in <%= @person.birth_year %> year

      <%# Checking Person's starships. If it exists, post it. %>
      <% if @person.starships.first %>
        <%# If it's only one starship, post it. %>
        <% if @person.starships.count == 1 %>
          and I have already piloted <%= @person.starships.first.name %>.
        <%# If it's two starships, post each name. %>
        <% elsif @person.starships.count == 2 %>
          and I have already piloted <%= @person.starships.first.name %> and <%= @person.starships.last.name %>.
        <% else %>
          <%= @person.starships.reduce("and I have already piloted") {|phrase, starship| phrase + " #{starship.name},"} %>
        <% end %>
      <%# If there is no starship, post no starship. %>
      <% else %>
        and I haven't piloted any starship.
      <% end %>

      <%# Checking Person's gender. If it exists, post it. %>
      <% if @person.gender != "n/a" %>
        I'm a <%= @person.gender %>
      <% else %>
        I'm an asexual
      <% end %>

      <%# Checking Person's eyes' color. If it exists, post it. %>
      <% if @person.eye_color %>
        with <%= @person.eye_color %> colored eyes
      <% end %>

      <%# Checking Person's hair' color. If it exists, post it. %>
      <% if @person.hair_color != "none" && @person.hair_color != "n/a" %>
        , <%= @person.hair_color %> colored hair
      <% else %>
        , no hair
      <% end %>

      <%# Checking Person's skin' color. If it exists, post it. %>
      <% if @person.skin_color %>
        and <%= @person.skin_color %> skin color.
      <% end %>

      <%# Checking Person's height. If it exists, post it. %>
      <% if @person.height %>
        I'm also <%= @person.height %> cm tall
      <% end %>

      <%# Checking Person's mass. If it exists, post it. %>
      <% if @person.mass %>
        and I weight <%= @person.mass %> KGs.
      <% end %>
    </h3>
</div>

app/views/planets/index.html.erb
<div class="row justify-content-center">
  <h1>
    Star Wars Planets
  </h1>
</div>
<div class="row justify-content-center">
  <% @planets.each do |planet| %>
    <div class="card m-3 col-10 col-md-3 col-lg-2">
      <div>
        <h2><%= link_to planet.name, planet_path(planet) %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/planets/show.html.erb
<div class="row justify-content-center">
  <h1 class="mt-3"><%= @planet.name %></h1>
</div>

<div class="mt-5 row card-show justify-content-center">
    <h3>
      This is <%= @planet.name %>.

      <%# Checking Planet's species. If it exists, post it. %>
      <% if @planet.species.first %>
        <%# If it's only one species, post it. %>
        <% if @planet.species.count == 1 %>
          It has the <%= @planet.species.first.name %> species living here.
        <%# If it's two species, post each name. %>
        <% elsif @planet.species.count == 2 %>
          It has the <%= @planet.species.first.name %> and <%= @planet.species.last.name %> species living here.
        <% else %>
          <%= @planet.species.reduce("It has the ") {|phrase, species| phrase + " #{species.name},"} %>
        <% end %>
      <% end %>

      <%# Checking Planet's population. If it exists, post it. %>
      <% if @planet.population != "none" && @planet.population != "unknown" && @planet.population != "0" %>
        It has a population of <%= @planet.population %> inhabitants.
      <% else %>
        No one lives here.
      <% end %>

      <%# Checking Planet's inhabitants. If it exists, post it. %>
      <% if @planet.people.first %>
        <%# If it's only one inhabitant, post it. %>
        <% if @planet.people.count == 1 %>
          The only one that lives here is <%= @planet.people.first.name %>.
        <%# If it's two inhabitants, post each name. %>
        <% elsif @planet.species.count == 2 %>
          There two inhabitants here: <%= @planet.people.first.name %> and <%= @planet.people.last.name %>.
        <% else %>
          <%= @planet.people.reduce("These are some that live here: ") {|phrase, person| phrase + " #{person.name},"} %>
        <% end %>
      <% end %>

      <%# Checking Planet's diameter. If it exists, post it. %>
      <% if @planet.diameter %>
        It has a diameter of <%= @planet.diameter %> km.
      <% end %>

      <%# Checking Planet's rotation_period. If it exists, post it. %>
      <% if @planet.rotation_period %>
        Regarding is rotation, it's period is <%= @planet.rotation_period %> hours
      <% end %>

      <%# Checking Planet's orbital_period. If it exists, post it. %>
      <% if @planet.orbital_period %>
        and its orbital period is <%= @planet.orbital_period %> days.
      <% end %>

      <%# Checking Planet's gravity. If it exists, post it. %>
      <% if @planet.gravity != "N/A" %>
        This planet's gravity is <%= @planet.gravity %>.
      <% else %>
        This planet's gravity is unknown.
      <% end %>

      <%# Checking Planet's climate. If it exists, post it. %>
      <% if @planet.climate %>
        It's climate is <%= @planet.climate %>
      <% end %>

      <%# Checking Planet's terrain. If it exists, post it. %>
      <% if @planet.terrain %>
        with a <%= @planet.terrain %> terrain
      <% end %>

      <%# Checking Planet's surface_water. If it exists, post it. %>
      <% if @planet.surface_water %>
        and it has <%= @planet.surface_water %> surface water.
      <% end %>
    </h3>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/fematarazzo/star_wars_app"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    Made with SWAPI by
    <a href="https://github.com/fematarazzo">Felipe Matarazzo</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to root_path do %>
    <%= image_tag "star-wars.png", alt: "Star Wars", class:"star-wars-avatar-square"%>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-3">
        <%= link_to "Characters", people_path %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "Planets", planets_path %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "Species", species_index_path %>
      </li>
      <li class="nav-item mx-3">
        <%= link_to "Starships", starships_path %>
      </li>
    </ul>
  </div>
</div>

app/views/species/index.html.erb
<div class="row justify-content-center">
  <h1>
    Star Wars Species
  </h1>
</div>
<div class="row justify-content-center">
  <% @species.each do |species| %>
    <div class="card m-3 col-10 col-md-3 col-lg-2">
      <div>
        <h2><%= link_to species.name, species_path(species) %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/species/show.html.erb
<div class="row justify-content-center">
  <h1 class="mt-3"><%= @species.name %></h1>
</div>



<div class="mt-5 row card-show justify-content-center">
    <h3>
      These are the <%= @species.name %>.

      <%# Checking Species' planet. If it exists, post it. %>
      <% if @species.planets.first %>
        <%# If it's only one species, post it. %>
        <% if @species.planets.count == 1 %>
          They live in <%= @species.planets.first.name %>.
        <%# If it's two species, post each name. %>
        <% elsif @species.planets.count == 2 %>
          They live in <%= @species.planets.first.name %> and <%= @species.planets.last.name %>.
        <% else %>
          <%= @species.planets.reduce("They live in ") {|phrase, planet| phrase + " #{planet.name},"} %>
        <% end %>
      <% end %>

      They are classified as <%= @species.classification %>.

      <%# Checking Species' people. If it exists, post it. %>
      <% if @species.people.first %>
        <%# If it's only one people, post it. %>
        <% if @species.people.count == 1 %>
          The only known person of this species is <%= @species.people.first.name %>.
        <%# If it's two people, post each name. %>
        <% elsif @species.people.count == 2 %>
          The couple of people known of this species are <%= @species.people.first.name %> and <%= @species.people.last.name %>.
        <% else %>
          <%= @species.people.reduce("These are some people of this species ") {|phrase, person| phrase + " #{person.name},"} %>
        <% end %>
      <% end %>

      Their designation is <%= @species.designation %>.
      Their average height is <%= @species.average_height %>
      and have an average lifespan of <%= @species.average_lifespan %> years.

      <%# Checking Species' language. If it exists, post it. %>
      <% if @species.language != "n/a"%>
        They speak <%= @species.language %>.
      <% else %>
        It's not known what languages they speak.
      <% end %>
    </h3>
</div>

app/views/starships/index.html.erb
<div class="row justify-content-center">
  <h1>
    Star Wars Starships
  </h1>
</div>
<div class="row justify-content-center">
  <% @starships.each do |starship| %>
    <div class="card m-3 col-10 col-md-3 col-lg-2">
      <div>
        <h2><%= link_to starship.name, starship_path(starship) %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/starships/show.html.erb
<div class="row justify-content-center">
  <h1 class="mt-3"><%= @starship.name %></h1>
</div>

<div class="mt-5 row card-show justify-content-center">
    <h3>
      This are the <%= @starship.name %> starship.

      It's model is <%= @starship.model %> with class <%= @starship.starship_class %> .

      <%# Checking Starship' people. If it exists, post it. %>
      <% if @starship.people.first %>
        <%# If it's only one people, post it. %>
        <% if @starship.people.count == 1 %>
          The only known person to ride this starship is <%= @starship.people.first.name %>.
        <%# If it's two people, post each name. %>
        <% elsif @starship.people.count == 2 %>
          The couple of people known to ride this starship are <%= @starship.people.first.name %> and <%= @starship.people.last.name %>.
        <% else %>
          <%= @starship.people.reduce("These are some people that rode this starship: ") {|phrase, person| phrase + " #{person.name},"} %>
        <% end %>
      <% end %>

      It's manufacturer by <%= @starship.manufacturer %> and costs <%= @starship.cost_in_credits %>.
      It's length is <%= @starship.length %>

      <%# Checking Starship' speed. If it exists, post it. %>
      <% if @starship.max_atmosphering_speed != "n/a"%>
        and it fly up to  <%= @starship.max_atmosphering_speed %> speed.
      <% else %>
        but it doesn't fly.
      <% end %>
    </h3>
</div>